### ISSUE TITLE
[BUG] Error: Frame was detached

### ISSUE THREAD

**Issue by SSK313** [Kaliiiiiiiiii-Vinyzu/patchright-python#3] opened 2024-11-12 13:12 UTC
**SYSTEM INFO-**

1. Patchright-  1.48.0.post0
2. OS- Windows 11
3. Browser- Chromium

I have been working on Instagram data scraper bot, switched to patchright from playwright given it's promising undetection features. The bot's playwright scraping code has been tested successfully for long operations but with patchright it's unexpectedly closing context after few extractions.

As usual the code is bulky, so will share only relevant parts. Feel free to ask for any relevant code snippets.

Context initialisation code is-
```
async def initialize_browser() -> tuple[Browser, BrowserContext]:
    # Ensure a user data directory exists for Patchright
    unique_user_data_dir = os.path.join(os.path.expanduser("~"), "Documents", "CustomChromeProfile")
    if not os.path.exists(unique_user_data_dir):
        os.makedirs(unique_user_data_dir)
    else:
        clear_old_data(unique_user_data_dir)

    logging.info(f"Using custom user data directory at: {unique_user_data_dir}")
    # Start Patchright's asynchronous context manager
    playwright = await async_playwright().start()
    
    # Launch a persistent context with recommended settings for undetectability
    context = await playwright.chromium.launch_persistent_context(
        user_data_dir=unique_user_data_dir,  # Path for persistent user data
        channel="chrome",             # Use Chrome for increased stealth
        headless=False,               # Use headless=False for more undetectable mode (change as needed)
        no_viewport=True,             # Disable viewport resizing for more natural behavior
        args=[
            "--window-size=1920,1080",
            
            "--disk-cache-size=500000000"
        ]
    )

    page = await context.new_page()
    logging.info("Custom Chrome profile initialized and page opened.")

    logging.info("Initialized Patchright Browser with persistent context and stealth mode enabled.")

    return context, page 
```
**Expected**
-Initialize the context with provided cookies
-Open the main scrolling page in primary tab
-Process collected post and profile links in a different tab

**Actual**
- It abruptly closes the context after 10-15 extraction
- The terminal log's point towards frame detachment

```
INFO:root:Total links collected so far: 36
C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\patchright\driver\package\lib\server\frames.js:606
    if (this.isDetached()) throw new Error('Frame was detached');
                                 ^

Error: Frame was detached
    at Frame._context (C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\patchright\driver\package\lib\server\frames.js:606:34)        

Node.js v20.18.0
Error encountered: Page.goto: Connection closed while reading from the driver
```
Help me out with this issue !!! Thanks

**Comment by Vinyzu** [comment] 2024-11-16 23:24
Thank you for your Issue!
I think i also got this error once or twice while testing, but it was pretty random.
Can you try to provide a reproducable example? Its quit hard to work on this when i cant reproduce it semi-frequently.

I have some ideas how to fix this but if you cant provide a reproducable code snippet ill push it to the end of my TODO due to time reasons

**Comment by Egsagon** [comment] 2024-11-24 19:04
It it helps, this error can be fixed by creating a new empty page after context initialisation.

```py
with plw.sync_playwright() as patch:
  ctx = patch.chromium.launch_persistent_context(...)
  ctx.new_page() # Avoid `frame detached` error
  yield ctx
```

I supposed that the page was closing/crashing and therefore the context would close, thus raising the error. But this is probably not the real reason since contexts already create an about:blank page on start.

**Comment by Vinyzu** [comment] 2024-12-08 22:57
This is temp-fixed, see [Patchright Commit](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright/commit/80663a5d04d323aa2a388ee9fa83979b5e5f00ea#diff-1d604a7e991a6961ce7fdcda29f3a9af07371ccd8cb72d9efac02a0dffadb9fbL451-R515).

This fix breaks [test_frames::test_evaluate_throw_for_detached_frames](https://github.com/microsoft/playwright-python/blob/main/tests/async/test_frames.py#L77-L89), but this will be resolved when Access from Isolated Script is introduced.
See the [Bugs Documentation](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright/issues/30) for more information.

**Closed by Vinyzu** 2024-12-08 22:57 UTC
Labels: bug, good first issue
