### ISSUE TITLE
[BUG] Page.goto: Connection closed while reading from the driver

### ISSUE THREAD

**Issue by mermyly** [Kaliiiiiiiiii-Vinyzu/patchright-python#6] opened 2024-11-25 21:09 UTC
When you loop through pages, the following error occurs: Exception: Page.goto: Connection closed while reading from the driver
```
browser = await pw.chromium.launch(headless=False)
context = await browser.new_context()
page = await context.new_page()
for _ in range(10):
    await page.goto("https://browserscan.net/")
    await asyncio.sleep(1)

await context.close()
await browser.close()
```

```
    if (this.isDetached()) throw new Error('Frame was detached');
                                 ^

Error: Frame was detached
    at Frame._context (C:\Users\mermyly\AppData\Local\pypoetry\Cache\virtualenvs\avito-parser-aOSDG-gG-py3.12\Lib\site-packages\patchright\driver\package\lib\server\frames.js:606:34)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:454:9)
    
     File "C:\Users\mermyly\AppData\Local\pypoetry\Cache\virtualenvs\avito-parser-aOSDG-gG-py3.12\Lib\site-packages\patchright\_impl\_connection.py", line 472, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
Exception: Page.goto: Connection closed while reading from the driver
```

**Comment by Vinyzu** [comment] 2024-12-08 22:54
Duplicate of https://github.com/Kaliiiiiiiiii-Vinyzu/patchright-python/issues/3

**Closed by Vinyzu** 2024-12-08 22:54 UTC
Labels: bug, duplicate
